### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by faxm0dem** [johanek/puppet-parse#11]
Hi, thanks for solving the previous issue. Now I have another one. Input manifest is the following:
```Puppet
class test (
  $plop = ["a"]
) {
test::plop { 'hey':
  foo => 'bar'
}

user { 'foo':
  uid => 1
}
}

class { 'test':
  plop => ["b"]
}
```
Command:
```
☠ ~/.gem/ruby/2.1.0/bin/puppet-parse /tmp/pff.pp
~/.gem/ruby/2.1.0/gems/rdoc-4.0.0.rc.2.1/lib/rdoc/markdown.rb:16321: warning: encountered \r in middle of line, treated as a mere space
```
Output:
```yaml
---
  test:
    parameters:
      plop:
    docs: {}
```
In my understanding, I was expecting the following:
```yaml
---
  test:
    parameters:
      plop:
        - b
  test::plop:
    hey:
      parameters:
        foo: bar
  user:
    foo:
      parameters:
        uid: 1
```
